server:
  port: 9090
application:
  ecnf:
    api:
      path: /ecnf/project-generator/v1.0/

spring:
  application:
    name: ecnf-project-generator
  main:
    allow-bean-definition-overriding: true

info:
  project:
    version: 1.0.0
    title: Data Retrieve Service
    description: Data retrieve service. Bring information about products, persons and derivates.



### custom yamel

